// <auto-generated />
using System;
using LMS_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512093202_SoftDeleteAssignments")]
    partial class SoftDeleteAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS_API.Models.AssignedAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedAssignmentSetId")
                        .HasColumnType("int");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentResultContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentResultFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentResultPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAssignmentSetId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignedAssignments");
                });

            modelBuilder.Entity("LMS_API.Models.AssignedAssignmentSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentSetId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfAssigned")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TaskDocumentContentType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TaskDocumentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TaskDocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentSetId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("AssignedAssignmentSets");
                });

            modelBuilder.Entity("LMS_API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("LMS_API.Models.AssignmentAssignmentSet", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("AssignmentSetId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId", "AssignmentSetId");

                    b.HasIndex("AssignmentSetId");

                    b.ToTable("AssignmentAssignmentSets");
                });

            modelBuilder.Entity("LMS_API.Models.AssignmentSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("AssignmentSets");
                });

            modelBuilder.Entity("LMS_API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedAssignmentSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LMS_API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByTeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByTeacherId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LMS_API.Models.StudentStudyClass", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudyClassId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "StudyClassId");

                    b.HasIndex("StudyClassId");

                    b.ToTable("StudentStudyClasses");
                });

            modelBuilder.Entity("LMS_API.Models.StudyClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudyClasses");
                });

            modelBuilder.Entity("LMS_API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("LMS_API.Models.AssignedAssignment", b =>
                {
                    b.HasOne("LMS_API.Models.AssignedAssignmentSet", "AssignedAssignmentSet")
                        .WithMany("AssignedAssignments")
                        .HasForeignKey("AssignedAssignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_API.Models.Assignment", "Assignment")
                        .WithMany("AssignedAssignments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedAssignmentSet");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("LMS_API.Models.AssignedAssignmentSet", b =>
                {
                    b.HasOne("LMS_API.Models.AssignmentSet", "AssignmentSet")
                        .WithMany()
                        .HasForeignKey("AssignmentSetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS_API.Models.Student", "Student")
                        .WithMany("AssignedAssignmentSets")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS_API.Models.Teacher", "Teacher")
                        .WithMany("AssignedAssignmentSets")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignmentSet");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS_API.Models.Assignment", b =>
                {
                    b.HasOne("LMS_API.Models.Teacher", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS_API.Models.AssignmentAssignmentSet", b =>
                {
                    b.HasOne("LMS_API.Models.Assignment", "Assignment")
                        .WithMany("AssignmentAssignmentSets")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_API.Models.AssignmentSet", "AssignmentSet")
                        .WithMany("AssignmentAssignmentSets")
                        .HasForeignKey("AssignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("AssignmentSet");
                });

            modelBuilder.Entity("LMS_API.Models.AssignmentSet", b =>
                {
                    b.HasOne("LMS_API.Models.Teacher", "Teacher")
                        .WithMany("AssignmentSets")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS_API.Models.Student", b =>
                {
                    b.HasOne("LMS_API.Models.Teacher", "CreatedByTeacher")
                        .WithMany("CreatedStudents")
                        .HasForeignKey("CreatedByTeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByTeacher");
                });

            modelBuilder.Entity("LMS_API.Models.StudentStudyClass", b =>
                {
                    b.HasOne("LMS_API.Models.Student", "Student")
                        .WithMany("StudentStudyClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_API.Models.StudyClass", "StudyClass")
                        .WithMany("StudentStudyClasses")
                        .HasForeignKey("StudyClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudyClass");
                });

            modelBuilder.Entity("LMS_API.Models.StudyClass", b =>
                {
                    b.HasOne("LMS_API.Models.Teacher", "Teacher")
                        .WithMany("StudyClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMS_API.Models.AssignedAssignmentSet", b =>
                {
                    b.Navigation("AssignedAssignments");
                });

            modelBuilder.Entity("LMS_API.Models.Assignment", b =>
                {
                    b.Navigation("AssignedAssignments");

                    b.Navigation("AssignmentAssignmentSets");
                });

            modelBuilder.Entity("LMS_API.Models.AssignmentSet", b =>
                {
                    b.Navigation("AssignmentAssignmentSets");
                });

            modelBuilder.Entity("LMS_API.Models.Student", b =>
                {
                    b.Navigation("AssignedAssignmentSets");

                    b.Navigation("StudentStudyClasses");
                });

            modelBuilder.Entity("LMS_API.Models.StudyClass", b =>
                {
                    b.Navigation("StudentStudyClasses");
                });

            modelBuilder.Entity("LMS_API.Models.Teacher", b =>
                {
                    b.Navigation("AssignedAssignmentSets");

                    b.Navigation("AssignmentSets");

                    b.Navigation("Assignments");

                    b.Navigation("CreatedStudents");

                    b.Navigation("StudyClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
