services:
  # 1. Database Service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ShoaibLovesHerMother-@Fkrs1234
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # 2. Backend Service
  api:
    build: ./LMS_API
    image: shoaibali808/csharp-lms-webapi:latest
    container_name: csharp_webapi
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=LMS;User Id=sa;Password=ShoaibLovesHerMother-@Fkrs1234;TrustServerCertificate=True;
      - Logging__Console__FormatterName=json
    depends_on:
      - db

  # 3. Frontend Service
  web:
    build: ./lms_frontend
    image: shoaibali808/vue-lms-frontend:latest
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  sql_data:
  prometheus_data:
  loki_data:
  grafana_data:
